class TurkeyCity {
  final int id;
  final String name;
  final String lowercaseName;

  TurkeyCity({required this.id, required this.name, required this.lowercaseName});
}

class TurkeyCityModel {
  static List<TurkeyCity> turkeyCities = [
    TurkeyCity(id: 1, name: "ADANA", lowercaseName: "adana"),
    TurkeyCity(id: 2, name: "ADIYAMAN", lowercaseName: "adiyaman"),
    TurkeyCity(id: 3, name: "AFYONKARAHİSAR", lowercaseName: "afyonkarahisar"),
    TurkeyCity(id: 4, name: "AĞRI", lowercaseName: "agri"),
    TurkeyCity(id: 68, name: "AKSARAY", lowercaseName: "aksaray"),
    TurkeyCity(id: 5, name: "AMASYA", lowercaseName: "amasya"),
    TurkeyCity(id: 6, name: "ANKARA", lowercaseName: "ankara"),
    TurkeyCity(id: 7, name: "ANTALYA", lowercaseName: "antalya"),
    TurkeyCity(id: 75, name: "ARDAHAN", lowercaseName: "ardahan"),
    TurkeyCity(id: 8, name: "ARTVİN", lowercaseName: "artvin"),
    TurkeyCity(id: 9, name: "AYDIN", lowercaseName: "aydin"),
    TurkeyCity(id: 10, name: "BALIKESİR", lowercaseName: "balikesir"),
    TurkeyCity(id: 74, name: "BARTIN", lowercaseName: "bartin"),
    TurkeyCity(id: 72, name: "BATMAN", lowercaseName: "batman"),
    TurkeyCity(id: 69, name: "BAYBURT", lowercaseName: "bayburt"),
    TurkeyCity(id: 11, name: "BİLECİK", lowercaseName: "bilecik"),
    TurkeyCity(id: 12, name: "BİNGÖL", lowercaseName: "bingol"),
    TurkeyCity(id: 13, name: "BİTLİS", lowercaseName: "bitlis"),
    TurkeyCity(id: 14, name: "BOLU", lowercaseName: "bolu"),
    TurkeyCity(id: 15, name: "BURDUR", lowercaseName: "burdur"),
    TurkeyCity(id: 16, name: "BURSA", lowercaseName: "bursa"),
    TurkeyCity(id: 17, name: "ÇANAKKALE", lowercaseName: "canakkale"),
    TurkeyCity(id: 18, name: "ÇANKIRI", lowercaseName: "cankiri"),
    TurkeyCity(id: 19, name: "ÇORUM", lowercaseName: "corum"),
    TurkeyCity(id: 20, name: "DENİZLİ", lowercaseName: "denizli"),
    TurkeyCity(id: 21, name: "DİYARBAKIR", lowercaseName: "diyarbakir"),
    TurkeyCity(id: 81, name: "DÜZCE", lowercaseName: "duzce"),
    TurkeyCity(id: 22, name: "EDİRNE", lowercaseName: "edirne"),
    TurkeyCity(id: 23, name: "ELAZIĞ", lowercaseName: "elazig"),
    TurkeyCity(id: 24, name: "ERZİNCAN", lowercaseName: "erzincan"),
    TurkeyCity(id: 25, name: "ERZURUM", lowercaseName: "erzurum"),
    TurkeyCity(id: 26, name: "ESKİŞEHİR", lowercaseName: "eskisehir"),
    TurkeyCity(id: 27, name: "GAZİANTEP", lowercaseName: "gaziantep"),
    TurkeyCity(id: 28, name: "GİRESUN", lowercaseName: "giresun"),
    TurkeyCity(id: 29, name: "GÜMÜŞHANE", lowercaseName: "gumushane"),
    TurkeyCity(id: 30, name: "HAKKARİ", lowercaseName: "hakkari"),
    TurkeyCity(id: 31, name: "HATAY", lowercaseName: "hatay"),
    TurkeyCity(id: 76, name: "IĞDIR", lowercaseName: "igdir"),
    TurkeyCity(id: 32, name: "ISPARTA", lowercaseName: "isparta"),
    TurkeyCity(id: 34, name: "İSTANBUL", lowercaseName: "istanbul"),
    TurkeyCity(id: 35, name: "İZMİR", lowercaseName: "izmir"),
    TurkeyCity(id: 46, name: "KAHRAMANMARAŞ", lowercaseName: "kahramanmaras"),
    TurkeyCity(id: 78, name: "KARABÜK", lowercaseName: "karabuk"),
    TurkeyCity(id: 70, name: "KARAMAN", lowercaseName: "karaman"),
    TurkeyCity(id: 36, name: "KARS", lowercaseName: "kars"),
    TurkeyCity(id: 37, name: "KASTAMONU", lowercaseName: "kastamonu"),
    TurkeyCity(id: 38, name: "KAYSERİ", lowercaseName: "kayseri"),
    TurkeyCity(id: 71, name: "KIRIKKALE", lowercaseName: "kirikkale"),
    TurkeyCity(id: 39, name: "KIRKLARELİ", lowercaseName: "kirklareli"),
    TurkeyCity(id: 40, name: "KIRŞEHİR", lowercaseName: "kirsehir"),
    TurkeyCity(id: 79, name: "KİLİS", lowercaseName: "kilis"),
    TurkeyCity(id: 41, name: "KOCAELİ", lowercaseName: "kocaeli"),
    TurkeyCity(id: 42, name: "KONYA", lowercaseName: "konya"),
    TurkeyCity(id: 43, name: "KÜTAHYA", lowercaseName: "kutahya"),
    TurkeyCity(id: 44, name: "MALATYA", lowercaseName: "malatya"),
    TurkeyCity(id: 45, name: "MANİSA", lowercaseName: "manisa"),
    TurkeyCity(id: 47, name: "MARDİN", lowercaseName: "mardin"),
    TurkeyCity(id: 33, name: "MERSİN", lowercaseName: "mersin"),
    TurkeyCity(id: 48, name: "MUĞLA", lowercaseName: "mugla"),
    TurkeyCity(id: 49, name: "MUŞ", lowercaseName: "mus"),
    TurkeyCity(id: 50, name: "NEVŞEHİR", lowercaseName: "nevsehir"),
    TurkeyCity(id: 51, name: "NİĞDE", lowercaseName: "nigde"),
    TurkeyCity(id: 52, name: "ORDU", lowercaseName: "ordu"),
    TurkeyCity(id: 80, name: "OSMANİYE", lowercaseName: "osmaniye"),
    TurkeyCity(id: 53, name: "RİZE", lowercaseName: "rize"),
    TurkeyCity(id: 54, name: "SAKARYA", lowercaseName: "sakarya"),
    TurkeyCity(id: 55, name: "SAMSUN", lowercaseName: "samsun"),
    TurkeyCity(id: 56, name: "SİİRT", lowercaseName: "siirt"),
    TurkeyCity(id: 57, name: "SİNOP", lowercaseName: "sinop"),
    TurkeyCity(id: 58, name: "SİVAS", lowercaseName: "sivas"),
    TurkeyCity(id: 63, name: "ŞANLIURFA", lowercaseName: "sanliurfa"),
    TurkeyCity(id: 73, name: "ŞIRNAK", lowercaseName: "sirnak"),
    TurkeyCity(id: 59, name: "TEKİRDAĞ", lowercaseName: "tekirdag"),
    TurkeyCity(id: 60, name: "TOKAT", lowercaseName: "tokat"),
    TurkeyCity(id: 61, name: "TRABZON", lowercaseName: "trabzon"),
    TurkeyCity(id: 62, name: "TUNCELİ", lowercaseName: "tunceli"),
    TurkeyCity(id: 64, name: "UŞAK", lowercaseName: "usak"),
    TurkeyCity(id: 65, name: "VAN", lowercaseName: "van"),
    TurkeyCity(id: 77, name: "YALOVA", lowercaseName: "yalova"),
    TurkeyCity(id: 66, name: "YOZGAT", lowercaseName: "yozgat"),
    TurkeyCity(id: 67, name: "ZONGULDAK", lowercaseName: "zonguldak"),
  ];
}
